action:
  auth_url: null
  components: null
  dry_run: false
  export_dir: null
  skip_os_cleanup: false
builder:
  build_base_images_if_not_exist: true
  keep_image_tree_consistency: true
  no_cache: false
  push: true
  workers: 8
configs:
  cron:
    rotate:
      days: 6
      interval: daily
      maxsize: 100M
      minsize: 1M
  db:
    max_timeout: 60
    root_password: password
  hindsight_heka_tcp_port:
    cont: 5565
  ingress:
    domain: external
    enabled: false
    port: 8443
  k8s_external_ip: 172.16.10.107
  mariadb:
    port:
      cont: 3306
  namespace: ccp
  openstack:
    project_name: admin
    role_name: admin
    user_name: admin
    user_password: password
  ovs_db:
    loglevel: info
  private_interface: ens3
  public_interface: ens4
  service:
    database: mariadb
  snap:
    log_level: 3
debug: false
default_log_levels:
- glanceclient=INFO
- keystoneauth=INFO
- neutronclient=INFO
- novaclient=INFO
- requests=WARN
- stevedore=INFO
- urllib3=WARN
files: {}
images:
  base_distro: debian
  base_images:
  - base
  - opencontrail-base
  base_tag: jessie
  image_specs: {}
  maintainer: MOS Microservices <mos-microservices@mirantis.com>
  namespace: ccp
  tag: newton
kubernetes:
  ca_cert: null
  cert_file: null
  insecure: null
  key_file: null
  namespace: ccp
  server: http://localhost:8080
log_file: null
nodes:
  ctl01:
    roles:
    - controller
    - openvswitch
  ctl0[2-3]:
    roles:
    - compute
    - openvswitch
registry:
  address: localhost:31500
  insecure: false
  password: ''
  timeout: 300
  username: ''
replicas: {}
repositories:
  clone: true
  clone_concurrency: 8
  path: /root/ccp-repos/
  skip_empty: true
roles:
  compute:
  - nova-compute
  - nova-libvirt
  controller:
  - etcd
  - glance-api
  - glance-registry
  - heat-api
  - heat-engine
  - horizon
  - keystone
  - mariadb
  - memcached
  - neutron-dhcp-agent
  - neutron-l3-agent
  - neutron-metadata-agent
  - neutron-server
  - nova-api
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - rabbitmq
  openvswitch:
  - neutron-openvswitch-agent
  - openvswitch-db
  - openvswitch-vswitchd
sources:
  openstack/cinder:
    git_ref: stable/newton
    git_url: https://github.com/openstack/cinder.git
  openstack/glance:
    git_ref: stable/newton
    git_url: https://github.com/openstack/glance.git
  openstack/heat:
    git_ref: stable/newton
    git_url: https://github.com/openstack/heat.git
  openstack/horizon:
    git_ref: stable/newton
    git_url: https://github.com/openstack/horizon.git
  openstack/keystone:
    git_ref: stable/newton
    git_url: https://github.com/openstack/keystone.git
  openstack/networking-calico:
    git_ref: master
    git_url: https://github.com/openstack/networking-calico.git
  openstack/neutron:
    git_ref: stable/newton
    git_url: https://github.com/openstack/neutron.git
  openstack/nova:
    git_ref: stable/newton
    git_url: https://github.com/openstack/nova.git
  openstack/requirements:
    git_ref: stable/newton
    git_url: https://git.openstack.org/openstack/requirements.git
  openstack/sahara-dashboard:
    git_ref: stable/newton
    git_url: https://git.openstack.org/openstack/sahara-dashboard.git
  projectcalico/calico:
    git_ref: 1.4.3
    git_url: https://github.com/projectcalico/felix.git
  projectcalico/libcalico:
    git_ref: v0.17.0
    git_url: https://github.com/projectcalico/libcalico.git
url:
  ceph:
    debian:
      keyid: 460F3994
      keyserver: hkp://keyserver.ubuntu.com:80
      repo: http://eu.ceph.com/debian-jewel
  debian: http://httpredir.debian.org/debian
  debian_security: http://security.debian.org
  mariadb:
    debian:
      keyid: '0xcbcb082a1bb943db'
      keyserver: hkp://keyserver.ubuntu.com:80
      repo: http://lon1.mirrors.digitalocean.com/mariadb/repo/10.1/debian
verbose_level: 1
versions:
  elasticsearch_curator_version: 4.1.0
  elasticsearch_version: 2.4.0
  etcd_version: v3.0.12
  grafana_version: 3.0.3-1463994644
  influxdb_version: 0.13.0
  kibana_version: 4.6.1
