configs:
  ceph:
    fsid: Changeme
    mon_host: Changeme
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-ceph
  name: fuel-ccp-ceph
url:
  ceph:
    debian:
      keyid: 460F3994
      keyserver: hkp://keyserver.ubuntu.com:80
      repo: http://eu.ceph.com/debian-jewel
