configs:
  cinder:
    api_port:
      cont: 8776
      ingress: volume
    ceph:
      backup_pool_name: backup
      enable: false
      key: Changeme
      pool_name: volumes
      rbd_secret_uuid: Changeme
      username: cinder
    db:
      name: cinder
      password: password
      username: cinder
    debug: false
    enabled_backends: rbd
    password: password
    username: cinder
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-cinder
  name: fuel-ccp-cinder
