configs:
  elasticsearch:
    cluster_port:
      cont: 9300
    port:
      cont: 9200
    retention_period: 30
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-searchlight
  name: fuel-ccp-searchlight
- git_url: https://git.openstack.org/openstack/fuel-ccp-stacklight
  name: fuel-ccp-stacklight
