configs:
  percona:
    cluster_name: "k8scluster"
    xtrabackup_password: "{{ control.database.xtrabackup_password }}"
    monitor_password: "{{ control.database.monitor_password }}"
    port:
      cont: 3306
  service:
    database: galera
  db:
    max_timeout: 60
    root_password: "{{ control.database.root_password }}"
url:
  percona:
    debian:
      repo: "http://repo.percona.com/apt"
      keyserver: "hkp://keyserver.ubuntu.com:80"
      keyid: "9334A25F8507EFA5"
