configs:
  glance:
    api_port:
      cont: 9292
      ingress: image
    bootstrap:
      enable: false
      image:
        disk_format: qcow2
        name: cirros
        url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    ceph:
      enable: false
      key: Changeme
      pool_name: images
      username: glance
    db:
      name: glance
      password: password
      username: glance
    debug: false
    password: password
    registry_port:
      cont: 9191
    swift:
      enable: false
      store_container: glance
      store_create_container_on_put: true
    user: glance
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-glance
  name: fuel-ccp-glance
