configs:
  heat:
    api_port:
      cont: 8004
      ingress: orchestration
    db:
      name: heat
      password: password
      username: heat
    debug: false
    password: password
    user: heat
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-heat
  name: fuel-ccp-heat
