configs:
  neutron:
    bootstrap:
      external:
        enable: false
        gateway: changeme
        nameserver: changeme
        net_name: ext-net
        network: changeme
        physnet: changeme
        pool:
          end: changeme
          start: changeme
        subnet_name: ext-subnet
      internal:
        enable: true
        gateway: 10.0.1.1
        net_name: int-net
        network: 10.0.1.0/24
        subnet_name: int-subnet
      router:
        name: ext-router
    calico:
      etcd_host: etcd-k8s
      etcd_port: 2379
    core_plugin: ml2
    db:
      name: neutron
      password: password
      username: neutron
    enable_lbaas: false
    enable_qos: false
    logging_debug: false
    ovsdb:
      connection: unix:/run/openvswitch/db.sock
      interface: native
    physnets:
    - bridge_name: br-ex
      flat: true
      interface: eth2
      name: physnet1
      vlan_range: false
    plugin_agent: openvswitch
    server_port:
      cont: 9696
      ingress: network
repos:
- git_url: https://git.openstack.org/openstack/fuel-ccp-neutron
  name: fuel-ccp-neutron
