configs:
  opencontrail:
    control_port:
      cont: 8083
    dns_introspect_port:
      cont: 8092
    dns_xmpp_port:
      cont: 8093
    named_port:
      cont: 53
    xmpp_port:
      cont: 5269
repos:
- git_url: https://github.com/Kshatrix/ccp-docker-opencontrail.git
  name: ccp-docker-opencontrail
files:
  # opencontrail-database
  cassandra.yaml: /srv/kubernetes/configmap/opencontrail-database/cassandra.yaml
  cassandra-env.sh: /srv/kubernetes/configmap/opencontrail-database/cassandra-env.sh
  contrail-database-nodemgr.conf: /srv/kubernetes/configmap/opencontrail-database/contrail-database-nodemgr.conf
  server.properties: /srv/kubernetes/configmap/opencontrail-database/server.properties
  zoo.cfg: /srv/kubernetes/configmap/opencontrail-database/zoo.cfg
  # opencontrail-config
  basicauthusers.properties: /srv/kubernetes/configmap/opencontrail-config/basicauthusers.properties
  contrail-config-nodemgr.ini: /srv/kubernetes/configmap/opencontrail-config/contrail-config-nodemgr.ini
  contrail-discovery.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-discovery.conf
  contrail-schema.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-schema.conf
  contrail-svc-monitor.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-svc-monitor.conf
  publisher.properties: /srv/kubernetes/configmap/opencontrail-config/publisher.properties
  contrail-api.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-api.conf
  contrail-device-manager.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-device-manager.conf
  contrail-keystone-auth.conf: /srv/kubernetes/configmap/opencontrail-config/contrail-keystone-auth.conf
  contrail-sudoers: /srv/kubernetes/configmap/opencontrail-config/contrail-sudoers
  log4j.properties: /srv/kubernetes/configmap/opencontrail-config/log4j.properties
  vnc-api-lib.ini: /srv/kubernetes/configmap/opencontrail-config/vnc-api-lib.ini
  # opecontrail webui
  config.global.js: /srv/kubernetes/configmap/opencontrail-web/config.global.js
  contrail-webui-userauth.js: /srv/kubernetes/configmap/opencontrail-web/contrail-webui-userauth.js
  # opencontrail control
  contrail-control.conf: /srv/kubernetes/configmap/opencontrail-control/contrail-control.conf
  contrail-control-nodemgr.conf: /srv/kubernetes/configmap/opencontrail-control/contrail-control-nodemgr.conf
  contrail-control-nodemgr.ini: /srv/kubernetes/configmap/opencontrail-control/contrail-control-nodemgr.ini
  contrail-dns.conf: /srv/kubernetes/configmap/opencontrail-control/contrail-dns.conf
  # opencontrail analytics
  contrail-alarm-gen.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-alarm-gen.conf
  contrail-analytics-nodemgr.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-analytics-nodemgr.conf
  contrail-collector.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-collector.conf
  contrail-snmp-collector.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-snmp-collector.conf
  contrail-analytics-api.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-analytics-api.conf
  contrail-analytics-nodemgr.ini: /srv/kubernetes/configmap/opencontrail-collector/contrail-analytics-nodemgr.ini
  contrail-query-engine.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-query-engine.conf
  contrail-topology.conf: /srv/kubernetes/configmap/opencontrail-collector/contrail-topology.conf
